name: Undocumented Check

on:
  push:
    branches: ["main", "dev"]
    paths:
      - "myosuite/**/*.py"
  pull_request:
    branches: ["main", "dev"]
    paths:
      - "myosuite/**/*.py"

permissions:
  contents: read

jobs:
  undocumented:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Find undocumented symbols
        run: python scripts/find_undocumented.py --path myosuite
